//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow.ChooseBestSubscription {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChooseBestSubscriptionRequest", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.Models")]
    [System.SerializableAttribute()]
    public partial class ChooseBestSubscriptionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWeekendIncludedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWholeDayImportantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainingsInWeekField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWeekendIncluded {
            get {
                return this.IsWeekendIncludedField;
            }
            set {
                if ((this.IsWeekendIncludedField.Equals(value) != true)) {
                    this.IsWeekendIncludedField = value;
                    this.RaisePropertyChanged("IsWeekendIncluded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWholeDayImportant {
            get {
                return this.IsWholeDayImportantField;
            }
            set {
                if ((this.IsWholeDayImportantField.Equals(value) != true)) {
                    this.IsWholeDayImportantField = value;
                    this.RaisePropertyChanged("IsWholeDayImportant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainingsInWeek {
            get {
                return this.TrainingsInWeekField;
            }
            set {
                if ((this.TrainingsInWeekField.Equals(value) != true)) {
                    this.TrainingsInWeekField = value;
                    this.RaisePropertyChanged("TrainingsInWeek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChooseBestSubscriptionResponse", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.Models")]
    [System.SerializableAttribute()]
    public partial class ChooseBestSubscriptionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanName {
            get {
                return this.PlanNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanNameField, value) != true)) {
                    this.PlanNameField = value;
                    this.RaisePropertyChanged("PlanName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChooseBestSubscription", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChooseBestSubscription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Workflow.ChooseBestSubscription.ChooseBestSubscriptionRequest paramField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Workflow.ChooseBestSubscription.ChooseBestSubscriptionRequest param {
            get {
                return this.paramField;
            }
            set {
                if ((object.ReferenceEquals(this.paramField, value) != true)) {
                    this.paramField = value;
                    this.RaisePropertyChanged("param");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChooseBestSubscription.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChooseBestSubscription", ReplyAction="http://tempuri.org/IService/ChooseBestSubscriptionResponse")]
        global::Workflow.ChooseBestSubscription.ChooseBestSubscriptionResponse1 ChooseBestSubscription(global::Workflow.ChooseBestSubscription.ChooseBestSubscriptionRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChooseBestSubscription", ReplyAction="http://tempuri.org/IService/ChooseBestSubscriptionResponse")]
        System.Threading.Tasks.Task<global::Workflow.ChooseBestSubscription.ChooseBestSubscriptionResponse1> ChooseBestSubscriptionAsync(global::Workflow.ChooseBestSubscription.ChooseBestSubscriptionRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChooseBestSubscriptionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Workflow.ChooseBestSubscription.ChooseBestSubscription ChooseBestSubscription;
        
        public ChooseBestSubscriptionRequest1() {
        }
        
        public ChooseBestSubscriptionRequest1(Workflow.ChooseBestSubscription.ChooseBestSubscription ChooseBestSubscription) {
            this.ChooseBestSubscription = ChooseBestSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChooseBestSubscriptionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1.Models", Order=0)]
        public Workflow.ChooseBestSubscription.ChooseBestSubscriptionResponse ChooseBestSubscriptionResponse;
        
        public ChooseBestSubscriptionResponse1() {
        }
        
        public ChooseBestSubscriptionResponse1(Workflow.ChooseBestSubscription.ChooseBestSubscriptionResponse ChooseBestSubscriptionResponse) {
            this.ChooseBestSubscriptionResponse = ChooseBestSubscriptionResponse;
        }
    }
}
